<a href="https://colab.research.google.com/github/raqueeb/TensorFlow2/blob/master/scikit_learn_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## সাইকিট-লার্ন এবং টেনসর ফ্লো, কোনটা দরকার?

In [0]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder


In [0]:
iris_data = load_iris() # load the iris dataset

print('Example data: ')
print(iris_data.data[:5])
print('Example labels: ')
print(iris_data.target[:5])


Example data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Example labels: 
[0 0 0 0 0]


In [0]:
x = iris_data.data
y_ = iris_data.target.reshape(-1, 1) # Convert data to a single column

# One Hot encode the class labels
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)

#print(y)

print(y[:5])



[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [0]:


from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam


# Split the data for training and testing
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)



In [0]:

# Build the model

model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='fc1'))
model.add(Dense(10, activation='relu', name='fc2'))
model.add(Dense(3, activation='softmax', name='output'))



In [0]:
# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])



In [0]:
print('Neural Network Model Summary: ')
print(model.summary())


Neural Network Model Summary: 
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
fc1 (Dense)                  (None, 10)                50        
_________________________________________________________________
fc2 (Dense)                  (None, 10)                110       
_________________________________________________________________
output (Dense)               (None, 3)                 33        
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________
None


In [0]:

# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=200)


Epoch 1/200
 - 0s - loss: 0.9181 - acc: 0.5667
Epoch 2/200
 - 0s - loss: 0.8042 - acc: 0.6667
Epoch 3/200
 - 0s - loss: 0.7340 - acc: 0.8167
Epoch 4/200
 - 0s - loss: 0.6852 - acc: 0.9000
Epoch 5/200
 - 0s - loss: 0.6386 - acc: 0.7667
Epoch 6/200
 - 0s - loss: 0.6036 - acc: 0.7833
Epoch 7/200
 - 0s - loss: 0.5738 - acc: 0.7833
Epoch 8/200
 - 0s - loss: 0.5445 - acc: 0.8750
Epoch 9/200
 - 0s - loss: 0.5256 - acc: 0.9000
Epoch 10/200
 - 0s - loss: 0.5001 - acc: 0.8667
Epoch 11/200
 - 0s - loss: 0.4861 - acc: 0.9083
Epoch 12/200
 - 0s - loss: 0.4674 - acc: 0.8667
Epoch 13/200
 - 0s - loss: 0.4476 - acc: 0.8917
Epoch 14/200
 - 0s - loss: 0.4329 - acc: 0.9250
Epoch 15/200
 - 0s - loss: 0.4105 - acc: 0.9583
Epoch 16/200
 - 0s - loss: 0.3834 - acc: 0.8500
Epoch 17/200
 - 0s - loss: 0.3836 - acc: 0.9167
Epoch 18/200
 - 0s - loss: 0.3535 - acc: 0.9000
Epoch 19/200
 - 0s - loss: 0.3304 - acc: 0.9583
Epoch 20/200
 - 0s - loss: 0.3168 - acc: 0.9750
Epoch 21/200
 - 0s - loss: 0.3089 - acc: 0.9750
E

In [0]:

# Test on unseen data

results = model.evaluate(test_x, test_y)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

30/30 [==============================] - 0s 3ms/step
Final test set loss: 0.016276
Final test set accuracy: 1.000000
